export const DEFAULT_MAX_CHARACTERS_PER_INTAKE_QUESTION = 300;

export const INTAKE_QUESTION_CHARACTER_LIMITS = {
  motivation: DEFAULT_MAX_CHARACTERS_PER_INTAKE_QUESTION,
  goal: DEFAULT_MAX_CHARACTERS_PER_INTAKE_QUESTION,
  background: DEFAULT_MAX_CHARACTERS_PER_INTAKE_QUESTION,
  industry: DEFAULT_MAX_CHARACTERS_PER_INTAKE_QUESTION,
} as const;
